name: Build and Release

on:
  push:
    tags:
      - 'v*'
   
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run package
      - run: npx vsce package -o jsonnet-renderer.vsix
      - uses: actions/upload-artifact@v4
        with:
          name: extension
          path: jsonnet-renderer.vsix

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extension
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            jsonnet-renderer.vsix
            scripts/bootstrap.ps1
